// Generated by `prospect emit ts` — do not edit.
//
// Types only, by design: the runtime client is hand-written and generic
// over `Procedures` below. Field names are camelCase here and snake_case
// on the wire; the client's generated mappers handle that, and they do
// NOT touch map keys, which are data.


export interface FeedInput {
  limit?: number
  cursor?: string | null
}

export interface FeedPage {
  posts: Post[]
  nextCursor?: string | null
}

export interface Post {
  id: string
  body?: string | null
  author: Author
  media?: MediaItem[]
  reactionCounts?: Record<string, number>
  commentCount: number
  createdAt: string
  editable?: boolean
  deletable?: boolean
}

export interface Author {
  name: string
  avatarKey?: string | null
}

export interface MediaItem {
  key: string
  contentType: string
  width?: number | null
  height?: number | null
}

export interface PostId {
  id: string
}

export interface CreatePostInput {
  body?: string | null
  media?: MediaItem[]
}

export interface UpdatePostInput {
  id: string
  body: string
}

export interface Empty {

}

export interface ThreadInput {
  postId: string
}

export interface CommentList {
  comments: Comment[]
}

export interface Comment {
  path: string
  depth: number
  body?: string | null
  author?: Author | null
  deleted?: boolean
  reactionCounts?: Record<string, number>
  createdAt: string
  editable?: boolean
  deletable?: boolean
}

export interface CreateCommentInput {
  postId: string
  body: string
  parentPath?: string | null
}

export interface UpdateCommentInput {
  postId: string
  path: string
  body: string
}

export interface CommentRef {
  postId: string
  path: string
}

export interface MyReactions {
  byTarget?: Record<string, string>
}

export interface ToggleReactionInput {
  postId: string
  target: string
  emoji: string
}

export interface ReactionState {
  target: string
  reactionCounts?: Record<string, number>
  mine?: string | null
}

export interface Profile {
  displayName?: string | null
  bio?: string | null
  avatarKey?: string | null
}

export interface UpdateProfileInput {
  displayName?: string | null
  bio?: string | null
  avatarKey?: string | null
}

export interface PresignInput {
  contentType: string
}

export interface PresignedUpload {
  url: string
  fields: Record<string, string>
  key: string
}


export type Procedures = {
  "comments.create": { kind: "mutation"; input: CreateCommentInput; output: Comment; error: NotFound | ValidationFailed }
  "comments.destroy": { kind: "mutation"; input: CommentRef; output: Comment; error: NotFound | Forbidden }
  "comments.thread": { kind: "query"; input: ThreadInput; output: CommentList; error: never }
  "comments.update": { kind: "mutation"; input: UpdateCommentInput; output: Comment; error: NotFound | Forbidden | ValidationFailed }
  "posts.create": { kind: "mutation"; input: CreatePostInput; output: Post; error: ValidationFailed }
  "posts.destroy": { kind: "mutation"; input: PostId; output: Empty; error: NotFound | Forbidden }
  "posts.feed": { kind: "query"; input: FeedInput; output: FeedPage; error: never }
  "posts.get": { kind: "query"; input: PostId; output: Post; error: NotFound }
  "posts.update": { kind: "mutation"; input: UpdatePostInput; output: Post; error: NotFound | Forbidden | ValidationFailed }
  "profiles.get": { kind: "query"; input: Empty; output: Profile; error: never }
  "profiles.update": { kind: "mutation"; input: UpdateProfileInput; output: Profile; error: ValidationFailed }
  "reactions.mine": { kind: "query"; input: ThreadInput; output: MyReactions; error: never }
  "reactions.toggle": { kind: "mutation"; input: ToggleReactionInput; output: ReactionState; error: NotFound | UnsupportedReaction }
  "uploads.presign": { kind: "mutation"; input: PresignInput; output: PresignedUpload; error: UnsupportedMediaType }
}


export interface NotFound {
  code: "not_found"
  resource: string
  id: string
}

export interface ValidationFailed {
  code: "validation_failed"
  errors: string
}

export interface Forbidden {
  code: "forbidden"
  action: string
  resource: string
}

export interface UnsupportedReaction {
  code: "unsupported_reaction"
  emoji: string
}

export interface UnsupportedMediaType {
  code: "unsupported_media_type"
  contentType: string
}


/** camelCase -> wire name, per type. Nothing else is renamed. */
export const WIRE_FIELDS: Record<string, Record<string, string>> = {
  UnsupportedMediaType: { contentType: "content_type" },
  FeedPage: { nextCursor: "next_cursor" },
  Post: { reactionCounts: "reaction_counts", commentCount: "comment_count", createdAt: "created_at" },
  Author: { avatarKey: "avatar_key" },
  MediaItem: { contentType: "content_type" },
  ThreadInput: { postId: "post_id" },
  Comment: { reactionCounts: "reaction_counts", createdAt: "created_at" },
  CreateCommentInput: { postId: "post_id", parentPath: "parent_path" },
  UpdateCommentInput: { postId: "post_id" },
  CommentRef: { postId: "post_id" },
  MyReactions: { byTarget: "by_target" },
  ToggleReactionInput: { postId: "post_id" },
  ReactionState: { reactionCounts: "reaction_counts" },
  Profile: { displayName: "display_name", avatarKey: "avatar_key" },
  UpdateProfileInput: { displayName: "display_name", avatarKey: "avatar_key" },
  PresignInput: { contentType: "content_type" },
}

/** Fields holding a nested struct (or list of one), for recursion. */
export const WIRE_NESTED: Record<string, Record<string, string>> = {
  FeedPage: { posts: "Post" },
  Post: { author: "Author", media: "MediaItem" },
  CreatePostInput: { media: "MediaItem" },
  CommentList: { comments: "Comment" },
  Comment: { author: "Author" },
}


/** Input/output type per procedure, so the client can map both directions. */
export const PROC_TYPES: Record<string, { input: string; output: string }> = {
  "comments.create": { input: "CreateCommentInput", output: "Comment" },
  "comments.destroy": { input: "CommentRef", output: "Comment" },
  "comments.thread": { input: "ThreadInput", output: "CommentList" },
  "comments.update": { input: "UpdateCommentInput", output: "Comment" },
  "posts.create": { input: "CreatePostInput", output: "Post" },
  "posts.destroy": { input: "PostId", output: "Empty" },
  "posts.feed": { input: "FeedInput", output: "FeedPage" },
  "posts.get": { input: "PostId", output: "Post" },
  "posts.update": { input: "UpdatePostInput", output: "Post" },
  "profiles.get": { input: "Empty", output: "Profile" },
  "profiles.update": { input: "UpdateProfileInput", output: "Profile" },
  "reactions.mine": { input: "ThreadInput", output: "MyReactions" },
  "reactions.toggle": { input: "ToggleReactionInput", output: "ReactionState" },
  "uploads.presign": { input: "PresignInput", output: "PresignedUpload" },
}


/** Wire error code -> interface name. */
export const ERROR_TYPES: Record<string, string> = {
  not_found: "NotFound",
  validation_failed: "ValidationFailed",
  forbidden: "Forbidden",
  unsupported_reaction: "UnsupportedReaction",
  unsupported_media_type: "UnsupportedMediaType",
}
