source "https://rubygems.org"

gem "prospect", path: "../../../prospect"
gem "dynamoid", "~> 3.10"
gem "aws-sdk-dynamodb", "~> 1"
gem "cancancan", "~> 3.6"

source "https://rubygems.omarqureshi.net" do
  gem "aws-cdk-lib", ">= 0.0.0.pre"
  gem "constructs", ">= 0.0.0.pre"
  gem "jsii-ruby-runtime", ">= 0.0.0.pre"
  gem "aws-cdk-asset-awscli-v1", ">= 0.0.0.pre"
  gem "aws-cdk-asset-node-proxy-agent-v6", ">= 0.0.0.pre"
  gem "aws-cdk-cloud-assembly-schema", ">= 0.0.0.pre"
end
